language: r
warnings_are_errors: true
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_BUILD_ARGS=" --compact-vignettes=gs+qpdf" 
     - R_CHECK_ARGS="--as-cran"
