language: r
r:
  - release
  - devel

cache: packages

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_BUILD_ARGS=" --compact-vignettes=gs+qpdf" 
     - R_CHECK_ARGS="--as-cran"
     - BOOTSTRAP_LATEX="1"
