language: r
sudo: false
cache: packages

r_build_args: "--compact-vignettes=gs+qpdf"

addons:
  apt:
    packages:
      - qpdf

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

repos:
  CRAN: https://cloud.r-project.org
  ropensci: https://packages.ropensci.org